# Generated by Django 3.1.7 on 2021-06-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('category_image', models.ImageField(blank=True, upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(default='', max_length=50)),
                ('upload_song', models.FileField(blank=True, upload_to='songs')),
                ('song_image', models.ImageField(blank=True, upload_to='images')),
                ('song_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapi.category')),
            ],
        ),
    ]
