# Generated by Django 3.1.7 on 2021-06-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='singer_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
